# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b392b7ec924efd96423e160cf79af1116c9759d18ee5d45e6eb386631156479e30f544fe04b2a5aaf5bc8877fd7c1ae9eb02e80cdfca776ccc02a17afc2325c

test:
  secret_key_base: fe60d94ce0482907bc1d76bd7c6d4ef4f24255b15cc9a5571a80c1d2f92a11fa34879958762a9529c63e4f6df1cfa9b6b342f8e003edafea4210836e6c9f0d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
